### ISSUE TITLE
Compile fails on Arch Linux 64-bit

### ISSUE THREAD

**Issue by JacobRoth** [cleanrock/flobby#37]
I tried compiling the latest flobby from git. cmake completed sucessfully, but when I run make, it crashes:
`[ 11%] Building CXX object src/gui/CMakeFiles/gui.dir/UserInterface.cpp.o
/home/yanom/flobby/src/gui/UserInterface.cpp: In member function ‘int UserInterface::run(int, char**)’:
/home/yanom/flobby/src/gui/UserInterface.cpp:217:9: error: ‘screen_work_area’ is not a member of ‘Fl’
         Fl::screen_work_area(x, y, w, h);
         ^~
src/gui/CMakeFiles/gui.dir/build.make:374: recipe for target 'src/gui/CMakeFiles/gui.dir/UserInterface.cpp.o' failed
make[2]: *** [src/gui/CMakeFiles/gui.dir/UserInterface.cpp.o] Error 1
CMakeFiles/Makefile2:416: recipe for target 'src/gui/CMakeFiles/gui.dir/all' failed
make[1]: *** [src/gui/CMakeFiles/gui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

any idea what's wrong here?

**Comment by cleanrock** [comment]
Looks like  Fl::screen_work_area was added in FLTK 1.3.1, I am a bit surprised about this since i thought flobby was ok to build with FLTK 1.3.0.
If you have a FLTK 1.3.0 or later try to add
#include <FL/Fl.H>
in UserInterface.cpp and report back here.

**Comment by cleanrock** [comment]
I now noticed you use arch which I develop and build on regularly, are you using fltk 1.3.3-6 from extra ?
Btw, you can also try my AUR package flobby-git.

**Comment by JacobRoth** [comment]
I've found the problem and corrected it. I was using fltk as provided by fltk-xcas, which was out of date. I removed xcas and fltk-xcas and installed regular ftlk, which compiles just fine.

the AUR package flobby-git lists fltk-xcas as a package that can satisfy flobby's fltk dependence, but this is incorrect I think...

Anyway, thanks for the help. I can launch flobby now.
